---
title: "Our course Report"
author: "Claudia Beleites"
date: "30 11 2021"
output: html_document
---

# Participants

- Hello I'm Claudia.

- Hi, I'm Ada A

- Hi, I'm Ada

- Hello I'am Anna.
- Hi I'm Patrycja
Ola hello
- Hi, I'm Karolina :)
- Hello I'm Sherouk.
- Hi I"m Kasia
- Hi I'm Sylvia

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(hyperSpec)
library(magrittr)
```

## Import Spectra

```{r import}
files <- Sys.glob("Spectra/*.spc")
print(files)

read.spc(files[1])

spectra <- list()
for (i in files) {
  spectra[[i]] <- read.spc(i)
  print(i)
}
spectra <- collapse(spectra)




```


Excursion: `lapply()`

```{r}
l <- lapply (1:3, function(x) x^2) 
l
```function(x) x^2)
... takes vector/list 1, 2, 3 and puts each element through square function. The result is in a `list()`.

We can collapse that list into a vector:
```{r}
unlist(l)
```

```{r}
sapply(1:3, function(x) x^2)
```

```{r}
length(1:3)
dim(spectra)
```

```{r}
spectra <- lapply(files, read.spc)
spectra <- collapse(spectra)
```

```{r}
spectra <- lapply(files, read.spc)
spectra <- collapse(spectra)
```

```{r}
spectra <- collapse(lapply(files, read.spc))

files %>% 
  lapply(read.spc) %>%
  collapse() -> spectra
```


```{r}
plot(spectra)
```

